spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    # prod 환경에서는 암호화
    username: haewon
    password: 000685
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # prod 환경에서는 in-memory DB 가 아니라는 전제 하에 create 대신 validate 수행
      ddl-auto: validate
  h2:
    console:
      enabled: false
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: false

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
