spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/autoever?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    # prod 환경에서는 해당 값 secret value
    password: ${AUTOEVER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # prod 환경에서는 in-memory DB 가 아니라는 전제 하에 create 대신 validate 수행
      ddl-auto: validate
  h2:
    console:
      enabled: false
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: false

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
