spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/autoever?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    # prod 환경에서는 해당 값 secret value
    password: ${AUTOEVER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    listener:
      simple:
        prefetch: 1
        concurrency: 2

springdoc:
  swagger-ui:
    enabled: false

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

admin:
  basic-auth:
    username: admin
    password: $2a$10$Qz49ajcCn2kdVuQesmsrPusnBQzq1QMHGBplKzsGqjSt1r4yOlXXC

api:
  kakao-talk:
    base-url: http://localhost:8081
    basic-auth:
      username: ${API_KAKAO_TALK_BASIC_AUTH_USERNAME}
      password: ${API_KAKAO_TALK_BASIC_AUTH_PASSWORD}
  sms:
    base-url: http://localhost:8082
    basic-auth:
      username: ${API_SMS_BASIC_AUTH_USERNAME}
      password: ${API_SMS_BASIC_AUTH_PASSWORD}

rabbit-mq:
  send-message:
    exchange: send-message-exchange
    kakao-talk-message-queue:
      name: kakao-talk-message-queue
      routing-key: kakao-talk-message-key
    sms-message-queue:
      name: sms-message-queue
      routing-key: sms-message-key