spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: haewon
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: true

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
