spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/autoever?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    # prod 환경에서는 해당 값 secret value
    password: ${AUTOEVER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

springdoc:
  swagger-ui:
    enabled: false

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

basic-auth:
  admin:
    username: admin
    password: $2a$10$Qz49ajcCn2kdVuQesmsrPusnBQzq1QMHGBplKzsGqjSt1r4yOlXXC